### ISSUE TITLE
The program jumps FileNotFoundException if the motor/sensor is removed.

### ISSUE THREAD

**Issue by a1aw** [mob41/ev3dev-lang-java#1]
This is a ~~critical bug~~ <b>Invalid Error Handling</b> in this API. Probably this problem exists as all the sub-classes (e.g. Sensor, Motor) <b>DOES NOT</b> extends the `Device` class.

<b>TODO:</b>
- [x] Make all sub-classes to be extended with `Device` class.
  - [x] Finish device class
  - [x] Extend `Motor` and its inherits
  - [x] Extend `Sensor` and its inherits
  - ~~Auto-reconnect function (Find `outA` addresses instead of something like `motor<N>`)~~ (No-longer required!)
- [x] A exception that handles like `DeviceNotExistException`
- [ ] Address Search Syntax

**Comment by a1aw** [comment]
No tests are being ran at this time.

**Comment by a1aw** [comment]
The commit [6e38ad5](https://github.com/mob41/ev3dev-lang-java/commit/2ea74b228916658d8010dce6758169bb3b96d33d) can easily lock the `Device` with a LegoPort and some class name (e.g. `tacho-motor`, `lego-sensor`)

**Comment by a1aw** [comment]
However, no tests were ran last 10 minutes. I am running tests on the recently commit 0534481d8998a85ff48818f517296dc9f273e528

**Comment by a1aw** [comment]
Test had failed 1/4. The motor can't auto-reconnect as the exception just stopped the thread.

**Comment by a1aw** [comment]
Test had failed 3/4. But, the motor can reconnect successfully. Yeah!

However, the file-system throws me a "Permission Denied" error. Delay?

```
Exception in thread "main" java.io.FileNotFoundException: /sys/class/tacho-motor/motor13/duty_cycle_sp (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:110)
        at java.io.PrintWriter.<init>(PrintWriter.java:184)
        at ev3dev.io.Sysclass.setProperty(Sysclass.java:102)
        at ev3dev.hardware.Device.setProperty(Device.java:134)
        at ev3dev.hardware.Device.setProperty(Device.java:118)
        at ev3dev.hardware.motors.Motor.setDutyCycleSP(Motor.java:201)
        at ev3dev.tests.TestOnEV3.main(TestOnEV3.java:18)
```

It is probably a bug?, or protection?

**Comment by a1aw** [comment]
Ha, this error `FileNotFoundException` of `No such file exist` SHOULD be exist. And the `connected` variable is only to be set when reading/writing to a property fails. Close.
